#! /bin/sh
##################### RUN SCRIPT FOR REFORMI #####################
#.... INPUT TO THE SCRIPT: 1 = MODEL, 2 = WAVE

#.... DIRECTORIES - EDIT TO AGREE WITH ACTUAL LOCATIONS

CODE_DIR=/home/john.lester/Documents/SAtlas_ODF/Code

DIR=`pwd`

#.... TEST TO SEE IF THE CORRECT NUMBER OF ARGUMENTS IS GIVEN

if [ $# -lt 2 ]; then
	echo "Usage:   run_reformi input_model wave"
	echo "EXAMPLE: run_reformi asunodfnew  0640 - NB - 4 DIGITS"
	exit 1
else
	MODEL=$1
	WAVE=$2
	MODEL_WAVE=$1_w$2
fi

#.... IF NEEDED, ESTABLISH THIS LINK

if [ $DIR != $CODE_DIR ]; then
	ln -s $CODE_DIR/reformi.exe          $DIR/reformi.exe
fi

#.... ESTABLISH SYMBOLIC LINKS

ln -s $DIR/specsyn_file31.$MODEL_WAVE    $DIR/specsyn.file31

ln -s $DIR/specsyn_file32.$MODEL_WAVE    $DIR/specsyn.file32

#.... EXECUTION

$DIR/reformi.exe

#.... REMOVE THIS SYMBOLIC LINK, IF NEEDED

if [ $DIR != $CODE_DIR ]; then
	rm $DIR/reformi.exe
fi

#.... ALWAYS REMOVE THESE SYMBOLIC LINKS

rm $DIR/specsyn.file3*

# MOVE THE OUTPUT TO SPECIFIC FILES

mv $DIR/reformi.print                    $DIR/reformi_print.$MODEL_WAVE

echo -ne '\a'

